// Generated by CoffeeScript 1.5.0
(function() {
  var app, bundle, gzippo, path, require;

  app = __meteor_bootstrap__.app, bundle = __meteor_bootstrap__.bundle, require = __meteor_bootstrap__.require;

  gzippo = require('gzippo');

  path = require('path');

  app.use(gzippo.staticGzip(path.join(bundle.root, 'static'), {
    prefix: '/cache',
    clientMaxAge: 1000 * 60 * 60 * 24 * 365
  }));

}).call(this);
